=== leviipope/personal-and-university-code/Other/XML/lego/lego.dtd
<!ELEMENT collection (set*)>
<!ATTLIST collection 
    username CDATA #REQUIRED>
<!ELEMENT set (name, code, pieces,price+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price
    currency CDATA #REQUIRED
    symbol CDATA #IMPLIED>
<!ELEMENT pieces (counter, (piece | minifig)*)>
<!ELEMENT counter (#PCDATA)>
<!ATTLIST counter minifig-count CDATA #REQUIRED>
<!ELEMENT piece (#PCDATA)>
<!ATTLIST piece code CDATA #REQUIRED>
<!ELEMENT minifig (#PCDATA)>
<!ATTLIST minifig code CDATA #REQUIRED>

=== leviipope/personal-and-university-code/Other/XML/lego/lego.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE collection SYSTEM "lego.dtd">
<?xml-stylesheet href="lego.css" type="text/css"?>
<collection username="leviipope">
    <set>
        <name>Mentoauto</name>
        <code>11111</code>
        <pieces>
            <counter minifig-count="3">185</counter>
            <piece code="1001">1x2 hosszu blokk</piece>
            <minifig code="1">Rendor figura</minifig>
            <minifig code="2">Tuzolto figura</minifig>
            <piece code="1000">3x4 blokk</piece>
        </pieces>
        <price currency="HUF">200000000</price>
        <price currency="USD" symbol="$">1</price>
    </set>
    <set>
        <name>Harry Potter</name>
        <code>22222</code>
        <pieces>
            <counter minifig-count="5">1850</counter>
        </pieces>
        <price currency="EUR" symbol="â‚¬">20000</price>
        <price currency="szotyi">100000000000000000</price>
    </set>
</collection>
